---
- name: Testing andrewrothstein.docker_binaries
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'docker --version'
      ansible.builtin.command: /usr/local/bin/docker --version
      changed_when: false
      register: docker_binaries_test_output
    - name: Output of 'docker --version'
      ansible.builtin.debug:
        msg: '{{ docker_binaries_test_output.stdout }}'
