---
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Checking for installation in {{ docker_binaries_ver_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ docker_binaries_ver_install_dir }}'
  changed_when: false
  register: docker_binaries_bin_dir
- name: Downloading and installing docker binaries
  when: not docker_binaries_bin_dir.stat.exists
  block:
    - name: Downloading {{ docker_binaries_url }} to {{ docker_binaries_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ docker_binaries_url }}'
        dest: '{{ docker_binaries_tmp_tgz }}'
        mode: '644'
        checksum: '{{ docker_binaries_checksum }}'

    - name: Mkdir {{ docker_binaries_ver_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ docker_binaries_ver_install_dir }}'
        state: directory
        mode: '755'

    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps

    - name: Unarchiving {{ docker_binaries_tmp_tgz }} to {{ docker_binaries_ver_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ docker_binaries_tmp_tgz }}'
        dest: '{{ docker_binaries_ver_install_dir }}'
        creates: '{{ docker_binaries_ver_install_subdir }}'
  always:
    - name: Rm {{ docker_binaries_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ docker_binaries_tmp_tgz }}'
        state: absent

- name: Link docker binaries from {{ docker_binaries_install_dir }} to {{ docker_binaries_ver_install_subdir }}
  become: true
  become_user: root
  with_items:
    - ctr
    - dockerd
    - docker-proxy
    - runc
    - containerd
    - docker-init
    - docker
  ansible.builtin.file:
    src: '{{ docker_binaries_ver_install_subdir }}/{{ item }}'
    dest: '{{ docker_binaries_install_dir }}/{{ item }}'
    state: link
