---
- include_role:
    name: andrewrothstein.unarchive-deps
- include_role:
    name: andrewrothstein.bash
- name: checking for installation in {{ docker_binaries_ver_install_dir }}
  become: true
  stat:
    path: '{{ docker_binaries_ver_install_dir }}'
  changed_when: false
  register: docker_binaries_bin_dir
- when: not docker_binaries_bin_dir.stat.exists
  block:
    - name: downloading  {{ docker_binaries_url }} to {{ docker_binaries_tmp_tgz }}
      become: true
      become_user: root
      get_url:
        url: '{{ docker_binaries_url }}'
        dest: '{{ docker_binaries_tmp_tgz }}'
        mode: 0644
        checksum: '{{ docker_binaries_checksum }}'

    - name: mkdir {{ docker_binaries_ver_install_dir }}
      become: true
      become_user: root
      file:
        path: '{{ docker_binaries_ver_install_dir }}'
        state: directory
        mode: 0755

    - name: unarchiving {{ docker_binaries_tmp_tgz }} to {{ docker_binaries_ver_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ docker_binaries_tmp_tgz }}'
        dest: '{{ docker_binaries_ver_install_dir }}'
        creates: '{{ docker_binaries_ver_install_subdir }}'
  always:
    - name: rm {{ docker_binaries_tmp_tgz }}
      become: true
      become_user: root
      file:
        path: '{{ docker_binaries_tmp_tgz }}'
        state: absent

- name: link docker binaries from {{ docker_binaries_install_dir }} to {{ docker_binaries_ver_install_subdir }}
  become: true
  become_user: root
  with_items:
    - ctr
    - dockerd
    - docker-proxy
    - runc
    - containerd
    - docker-init
    - docker
  file:
    src: '{{ docker_binaries_ver_install_subdir }}/{{ item }}'
    dest: '{{ docker_binaries_install_dir }}/{{ item }}'
    state: link
